DECLARE
    N_SALES      NUMBER;
    N_COMMISSION NUMBER;
BEGIN
    N_SALES := 120000;
    IF N_SALES > 100000 THEN
        N_COMMISSION := 0.2;
        GOTO ZERO_COMMISSION;
    ELSIF N_SALES > 50000 THEN
        N_COMMISSION := 0.15;
    ELSIF N_SALES > 20000 THEN
        N_COMMISSION := 0.1;
    ELSE
        <<ZERO_COMMISSION>>
        N_COMMISSION := 0;
    END IF;
END;